export const CONTRACT_CLAUSES = [
  {
    number: "1",
    title: "Grant of Rights",
    body: `The Artist hereby grants to OrinlabÍ Records a non-exclusive, worldwide licence to distribute, reproduce, transmit, and make available the Release and its associated artwork and metadata on digital streaming and download platforms ("Digital Service Providers" or "DSPs"), including but not limited to Spotify, Apple Music, TikTok, YouTube Music, Amazon Music, Boomplay, Audiomack, Deezer, and TIDAL, for the duration of the Term. This licence is granted solely for the purposes of digital distribution and does not transfer ownership of any master recording, sound recording copyright, underlying musical composition, or any other intellectual property right to OrinlabÍ Records.`,
  },
  {
    number: "2",
    title: "Term & Renewal",
    body: `This Agreement commences on the Effective Date and continues for an initial period of two (2) years (the "Initial Term"). Upon expiry of the Initial Term, this Agreement shall automatically renew for successive periods of one (1) year each (each a "Renewal Term"), unless either party provides the other with written notice of non-renewal at least sixty (60) days prior to the end of the then-current term. The Artist may request early termination by submitting written notice via the Artist Portal; such termination shall take effect ninety (90) days from receipt of notice, during which all distribution services shall continue on normal terms.`,
  },
  {
    number: "3",
    title: "Revenue Share & Royalties",
    body: `(a) Free First Release. The Artist's first release distributed through OrinlabÍ Records (the "First Release") shall be distributed at no cost. OrinlabÍ Records shall charge no distribution service fee on the First Release. The Artist shall receive and retain one hundred percent (100%) of Net Revenue generated by the First Release for the entire duration this Agreement remains in force.

(b) Subsequent Releases — Standard Distribution Fee. For the Artist's second and all subsequent releases submitted and distributed through OrinlabÍ Records, OrinlabÍ Records shall remit eighty-five percent (85%) of Net Revenue to the Artist and shall retain fifteen percent (15%) of Net Revenue as its standard distribution service fee. This fee covers delivery to all DSPs, ISRC/UPC management, metadata maintenance, royalty collection, and Artist Portal access.

(c) Definition of Net Revenue. "Net Revenue" means the gross revenue actually received by OrinlabÍ Records from DSPs in respect of streams, downloads, and other digital monetisation of the Release, less any withholding taxes, mandatory banking transfer fees, currency conversion charges, or deductions imposed by DSPs or payment processors on amounts remitted to OrinlabÍ Records. Net Revenue does not include amounts collected on behalf of third parties (e.g. publishing societies) or amounts subject to a separate written agreement.

(d) Royalty Reporting. OrinlabÍ Records shall provide the Artist with digital royalty statements on a quarterly basis, detailing per-platform stream counts, gross revenue, applicable deductions, and the Artist's net share. Statements shall be made available through the Artist Portal within forty-five (45) days of the close of each calendar quarter.

(e) Payment of Royalties. OrinlabÍ Records shall process payment of accrued royalties when the Artist's cumulative unpaid balance equals or exceeds fifty United States Dollars (USD $50.00). Payment shall be made within thirty (30) days of the close of the applicable quarter via the Artist's registered payment method. Balances below USD $50.00 shall roll forward to the following quarter without penalty.`,
  },
  {
    number: "4",
    title: "Artist Representations & Warranties",
    body: `The Artist represents, warrants, and covenants to OrinlabÍ Records that: (a) the Artist is the sole and exclusive owner of, or has obtained all necessary licences and clearances in respect of, all rights in the Release, including all master recording rights, underlying musical composition rights, lyrical rights, and any sampled material; (b) the Release does not infringe any third-party intellectual property right, violate any right of publicity or privacy, constitute defamation, or breach any applicable law or regulation in any jurisdiction; (c) the Artist has full legal capacity and authority to enter into this Agreement and to grant all rights herein; (d) all featured artists, co-writers, producers, and other contributors have provided their written consent to the distribution of the Release under this Agreement; (e) the Release has not been distributed in a manner that would conflict with the rights granted herein; and (f) all metadata, credits, and copyright information provided by the Artist are accurate and complete.`,
  },
  {
    number: "5",
    title: "Delivery Standards & Metadata",
    body: `The Artist shall deliver the Release in the format, quality specifications, and accompanying documentation required by OrinlabÍ Records from time to time, including without limitation: a WAV or FLAC audio file of no less than 16-bit / 44.1 kHz quality; cover artwork of no less than 3,000 × 3,000 pixels in JPEG or PNG format; accurate and complete metadata including ISRC codes (or consent for OrinlabÍ Records to obtain same), songwriter credits, producer credits, publishing information, and release date. OrinlabÍ Records shall not be liable for errors, delays, or failures in distribution caused by inaccurate, incomplete, or non-conforming metadata or files provided by the Artist. OrinlabÍ Records reserves the right to reject a submission that does not meet these standards, and shall notify the Artist with reasons within five (5) business days.`,
  },
  {
    number: "6",
    title: "Content Compliance & Takedowns",
    body: `The Artist agrees not to submit Releases that contain unlicensed samples, infringing content, hate speech, content that sexualises minors, or material that violates any applicable law. If a DSP issues a takedown, content dispute, or copyright claim in respect of the Release, OrinlabÍ Records shall notify the Artist promptly. The Artist shall cooperate fully and promptly to resolve such disputes. OrinlabÍ Records reserves the right to remove a Release from distribution platforms without prior notice if it receives a valid legal demand, a sustained copyright infringement claim, or determines in its reasonable opinion that continued distribution presents a legal risk. Any royalties accrued prior to such removal shall be paid to the Artist in accordance with Clause 3.`,
  },
  {
    number: "7",
    title: "Termination",
    body: `Either party may terminate this Agreement upon sixty (60) days' prior written notice. In addition, OrinlabÍ Records may terminate this Agreement immediately upon written notice if the Artist: (i) materially breaches this Agreement and fails to cure such breach within fourteen (14) days of written notice; (ii) provides materially false representations; or (iii) engages in conduct that brings OrinlabÍ Records into disrepute. Upon termination, OrinlabÍ Records shall initiate the takedown of the Release from all DSPs within thirty (30) business days of the effective termination date. Royalties accrued and payable prior to the effective termination date shall be remitted to the Artist within ninety (90) days thereof.`,
  },
  {
    number: "8",
    title: "Intellectual Property & Credits",
    body: `The Artist retains full ownership of all intellectual property in the Release, including the sound recording copyright and the underlying musical composition. OrinlabÍ Records acquires no ownership interest by virtue of this Agreement. The Artist acknowledges that DSPs may display distributor credits (℗ and © lines) and consents to OrinlabÍ Records supplying its name as distributor to DSPs where required by their ingestion processes. This does not constitute a claim of ownership. OrinlabÍ Records shall not register any copyright, trademark, or other intellectual property in the Artist's name or in respect of the Release.`,
  },
  {
    number: "9",
    title: "Limitation of Liability",
    body: `To the maximum extent permitted by applicable law: (a) OrinlabÍ Records's aggregate liability to the Artist under or in connection with this Agreement shall not exceed the total Net Revenue remitted to the Artist in the six (6) calendar months immediately preceding the event giving rise to the claim; (b) OrinlabÍ Records shall not be liable for any indirect, incidental, consequential, special, or punitive damages, including but not limited to loss of profits, loss of revenue, loss of data, or loss of business opportunity, whether arising in contract, tort (including negligence), or otherwise, even if OrinlabÍ Records has been advised of the possibility of such damages; (c) OrinlabÍ Records shall not be liable for delays or failures in distribution caused by the technical systems of DSPs, force majeure events, or the Artist's failure to deliver conforming files or metadata.`,
  },
  {
    number: "10",
    title: "Confidentiality",
    body: `Each party agrees to treat as confidential any non-public information received from the other party in connection with this Agreement, including royalty statements, business terms, and Artist analytics. Neither party shall disclose such information to third parties without the other's prior written consent, except as required by applicable law, regulation, or court order, in which case the disclosing party shall provide prompt notice to the other party where legally permitted.`,
  },
  {
    number: "11",
    title: "Governing Law & Dispute Resolution",
    body: `This Agreement shall be governed by and construed in accordance with the laws of the Federal Republic of Nigeria. In the event of any dispute arising out of or relating to this Agreement, the parties agree first to attempt resolution through good-faith negotiation for a period of thirty (30) days. If the dispute is not resolved through negotiation, it shall be submitted to mediation. If mediation fails, the dispute shall be subject to the exclusive jurisdiction of the competent courts of Lagos State, Nigeria. Nothing in this clause prevents either party from seeking emergency injunctive or interim relief from a court of competent jurisdiction.`,
  },
  {
    number: "12",
    title: "Entire Agreement & Amendments",
    body: `This Agreement constitutes the entire agreement between the parties with respect to its subject matter and supersedes all prior negotiations, representations, warranties, and understandings. No amendment to this Agreement shall be binding unless made in writing and signed by authorised representatives of both parties. OrinlabÍ Records may update its standard distribution terms from time to time; material changes shall be notified to the Artist via the Artist Portal no less than thirty (30) days before they take effect, and the Artist's continued use of the service after such period shall constitute acceptance.`,
  },
];
